'------------------------------------------------------------------------------
' <auto-generated>
'     Dieser Code wurde von einem Tool generiert.
'     Laufzeitversion:4.0.30319.42000
'
'     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
'     der Code erneut generiert wird.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    '-Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    'Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    'mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    '''<summary>
    '''  Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("Metropolis_Launcher.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        '''  Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die &lt;doc&gt;
        '''  &lt;chm&gt;ml.chm&lt;/chm&gt;
        '''  &lt;web&gt;http://emulation-evolved.net/mlhelp/&lt;/web&gt;
        '''  &lt;entry&gt;
        '''    &lt;form&gt;frm_Login&lt;/form&gt;
        '''    &lt;control&gt;
        '''    &lt;/control&gt;
        '''    &lt;topic&gt;login.htm&lt;/topic&gt;
        '''    &lt;anchor&gt;login.htm&lt;/anchor&gt;
        '''  &lt;/entry&gt;
        '''  &lt;entry&gt;
        '''    &lt;form&gt;frm_Main&lt;/form&gt;
        '''    &lt;control&gt;
        '''    &lt;/control&gt;
        '''    &lt;topic&gt;welcome.htm&lt;/topic&gt;
        '''    &lt;anchor&gt;
        '''    &lt;/anchor&gt;
        '''  &lt;/entry&gt;
        '''  &lt;entry&gt;
        '''    &lt;form&gt;frm_Main&lt;/form&gt;
        '''    &lt;control&gt;ucr_Emulation;grd_Emu_Games&lt;/control&gt;
        '''    &lt;topic&gt;games__emulation_main_screen.htm&lt;/topic&gt;
        '''     [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        '''</summary>
        Friend ReadOnly Property helpmap() As String
            Get
                Return ResourceManager.GetString("helpmap", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die ;
        '''; Metropolis Launcher AutoHotKey Support v1.0
        '''; based on AutoHotKey Version 1.1.29.01
        ''';
        '''; Script Function:
        ''';	This is a template script
        ''';	Use it as the starting point for developing your own script
        '''
        '''mlEMUDIR := &quot;&quot;          ; the directory of the emulator
        '''mlEMUEXE := &quot;&quot;          ; the executable of the emulator
        '''mlEMUFULLPATH := &quot;&quot;     ; the full path (emudir \ emuexe) of the emulator
        '''mlLISTFILE := &quot;&quot;        ; full path to the generated list file
        '''
        '''mlNUMBEROFROMS := 0     ; total number of roms
        ''' [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        '''</summary>
        Friend ReadOnly Property ml_autohotkey_template() As String
            Get
                Return ResourceManager.GetString("ml_autohotkey_template", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Zeichenfolge, die #include &lt;Constants.au3&gt;
        '''
        ''';
        '''; Metropolis Launcher AutoIt Support v1.0
        '''; based on AutoIt Version 3
        ''';
        '''; Script Function:
        ''';	This is a template script
        ''';	Use it as the starting point for developing your own script
        '''
        '''Global $mlEMUDIR			; the directory of the emulator
        '''Global $mlEMUEXE			; the executable of the emulator
        '''Global $mlEMUFULLPATH		; the full path (emudir \ emuexe) of the emulator
        '''Global $mlLISTFILE			; full path to the generated list file
        '''
        '''Global $mlNUMBEROFROMS		; total number of roms
        '''
        ''' [Rest der Zeichenfolge wurde abgeschnitten]&quot;; ähnelt.
        '''</summary>
        Friend ReadOnly Property ml_autoit_template() As String
            Get
                Return ResourceManager.GetString("ml_autoit_template", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Sucht eine lokalisierte Ressource vom Typ System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property pen_white() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("pen_white", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
    End Module
End Namespace
